In [46]:

import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import time

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe


print('Libraries imported.')

Libraries imported.

In [47]:
Jobs = pd.read_csv('indeed.csv')
Jobs.head()

,Title,Location,Company
0,"Data Scientist, Video Analytics","Oakville, ON",Geotab
1,Tech- Data Scientist & Client Integration Asso...,"Toronto, ON",Exiger
2,Data Scientist/Bioinformatician,"Toronto, ON",SickKids
3,data scientist,"Vancouver, BC","ResponsiveAds, Inc."
4,Sr Data Scientist,"Kirkland, QC",IQVIA

## cleaning Data

In [48]:
# Separate City and Province from Location
Jobs1 = pd.concat([Jobs['Title'],Jobs['Company'], Jobs['Location'].str.split(', ', expand=True), ], axis=1)

In [49]:
Jobs1.head()

,Title,Company,0,1
0,"Data Scientist, Video Analytics",Geotab,Oakville,ON
1,Tech- Data Scientist & Client Integration Asso...,Exiger,Toronto,ON
2,Data Scientist/Bioinformatician,SickKids,Toronto,ON
3,data scientist,"ResponsiveAds, Inc.",Vancouver,BC
4,Sr Data Scientist,IQVIA,Kirkland,QC

In [50]:
Jobs1.columns = ['Job Title', 'Company Name', 'City', 'Province Code']
Jobs1.to_csv("cleanIndeed.csv",index=False)

# Tableau Results: 
## Tableau is a visual analytics platform which helps to understand the data faster and better with many chart options. 
<img src="bubble.png" width=400 height=600 align="center"/>
<img src="textTable.png" width=400 height=600 align="center"/>
<img src="sidebyside.png" width=1000 height=700 align="center"/>

 ## Findings
Based on the above Charts, I found that Ontario Province has large number of Data science related openings and Toronto is the capital city of Ontario Province, it has much more jobs. I am very happy with the findings of the above. Ontario province is the best option for me to immigrate.

In [51]:
Jobs1.head()

,Job Title,Company Name,City,Province Code
0,"Data Scientist, Video Analytics",Geotab,Oakville,ON
1,Tech- Data Scientist & Client Integration Asso...,Exiger,Toronto,ON
2,Data Scientist/Bioinformatician,SickKids,Toronto,ON
3,data scientist,"ResponsiveAds, Inc.",Vancouver,BC
4,Sr Data Scientist,IQVIA,Kirkland,QC

In [52]:
Jobs1.shape

(1870, 4)

### Droping unwanted columns

I have already found the city based on large number of job openings. Toronto is the suitable city for me to move. I would like to drop Job Title column and only keeping toronto city.

In [53]:
Jobs2 = Jobs1.drop(['Job Title'], axis=1)
Jobs2.head()

          Company Name       City Province Code
0               Geotab   Oakville            ON
1               Exiger    Toronto            ON
2             SickKids    Toronto            ON
3  ResponsiveAds, Inc.  Vancouver            BC
4                IQVIA   Kirkland            QC

In [54]:
# removing nan 
Jobs2.dropna(inplace= True)
Jobs2.shape # it was 1870 rows and 1848 after removing nan

(1848, 3)

In [55]:
#removing all cities except Toronto
Jobs2 = Jobs2.loc[Jobs2['City'] == 'Toronto']
Jobs2.head()

   Company Name     City Province Code
1        Exiger  Toronto            ON
2      SickKids  Toronto            ON
11     Coursera  Toronto            ON
15        TKEES  Toronto            ON
20     SickKids  Toronto            ON

In [56]:
Jobs2.shape

(627, 3)

In [57]:
# assending order of company names
Jobs2.sort_values("Company Name", axis= 0, ascending = True, inplace = True, kind= 'quicksort', na_position= 'last')
Jobs2.head()

                       Company Name     City Province Code
280  AMZN CAN Fulfillment Svcs, ULC  Toronto            ON
169  AMZN CAN Fulfillment Svcs, ULC  Toronto            ON
185  AMZN CAN Fulfillment Svcs, ULC  Toronto            ON
402  AMZN CAN Fulfillment Svcs, ULC  Toronto            ON
26   AMZN CAN Fulfillment Svcs, ULC  Toronto            ON

In [58]:
#we can see that Jobs2 dataframe has multiple Job openings within the same company
#let's remove duplicates
Jobs3 = Jobs2.drop_duplicates()
Jobs3

                             Company Name     City Province Code
280        AMZN CAN Fulfillment Svcs, ULC  Toronto            ON
57                              Accenture  Toronto            ON
474                           BFS Capital  Toronto            ON
307                   BMO Financial Group  Toronto            ON
525   BMW Group Financial Services Canada  Toronto            ON
983                              Birdseye  Toronto            ON
487                             Capgemini  Toronto            ON
1055                             Ceridian  Toronto            ON
117                Colliers International  Toronto            ON
63                               Coursera  Toronto            ON
541                            Desjardins  Toronto            ON
569                            Enhance IT  Toronto            ON
1                                  Exiger  Toronto            ON
191              HarperCollins Publishers  Toronto            ON
458                                Intact  Toronto            ON
570                        Loblaw Digital  Toronto            ON
361                             PagerDuty  Toronto            ON
724              Patriot One Technologies  Toronto            ON
1843               Postmedia Network Inc.  Toronto            ON
1855          Qode Social Media Marketing  Toronto            ON
215                                   RBC  Toronto            ON
99                               Resolver  Toronto            ON
1340                    Saatchi & Saatchi  Toronto            ON
2                                SickKids  Toronto            ON
256                               TD Bank  Toronto            ON
161                                 TKEES  Toronto            ON
1675                          Tenstorrent  Toronto            ON
1226                             VersaPay  Toronto            ON

In [59]:
Jobs3.shape

(28, 3)

In [60]:
# reset index
Jobs3.reset_index(drop = True)
Jobs3.to_excel("company1.xlsx",index=False)

# get latitude and longitude of each company using geocode

In [61]:
#merge columns using Concat
df1 = pd.DataFrame(columns = ['Address'])
df1['Address'] = pd.concat([Jobs3["Company Name"] + " , " + Jobs3["City"] + " , "+ Jobs3["Province Code"]], ignore_index= True, sort= False)
df1.to_excel("company.xlsx",index=False)
df1

                                              Address
0       AMZN CAN Fulfillment Svcs, ULC , Toronto , ON
1                            Accenture , Toronto , ON
2                          BFS Capital , Toronto , ON
3                  BMO Financial Group , Toronto , ON
4   BMW Group Financial Services Canada , Toronto ...
5                             Birdseye , Toronto , ON
6                            Capgemini , Toronto , ON
7                             Ceridian , Toronto , ON
8               Colliers International , Toronto , ON
9                             Coursera , Toronto , ON
10                          Desjardins , Toronto , ON
11                          Enhance IT , Toronto , ON
12                              Exiger , Toronto , ON
13            HarperCollins Publishers , Toronto , ON
14                              Intact , Toronto , ON
15                      Loblaw Digital , Toronto , ON
16                           PagerDuty , Toronto , ON
17            Patriot One Technologies , Toronto , ON
18              Postmedia Network Inc. , Toronto , ON
19         Qode Social Media Marketing , Toronto , ON
20                                 RBC , Toronto , ON
21                            Resolver , Toronto , ON
22                   Saatchi & Saatchi , Toronto , ON
23                            SickKids , Toronto , ON
24                             TD Bank , Toronto , ON
25                               TKEES , Toronto , ON
26                         Tenstorrent , Toronto , ON
27                            VersaPay , Toronto , ON

In [62]:
!pip install googlemaps

from googlemaps import Client as GoogleMaps
import pandas as pd

Requirement already satisfied: googlemaps in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (4.4.2)
Requirement already satisfied: requests<3.0,>=2.20.0 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from googlemaps) (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)

In [63]:
gmaps = GoogleMaps('AIzaSyAj1CL9DS0fmhPmYqnLYkcdhFZdSW_RlTk')
addresses = pd.read_excel("company.xlsx")
addresses['lat'] = ""
addresses['long'] = ""
for x in range(len(addresses)):
    try:
        geocode_result = gmaps.geocode(addresses['Address'][x])
        addresses['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
        addresses['long'][x] = geocode_result[0]['geometry']['location']['lng']
    except IndexError:
        print("Address was wrong...")
    except Exception as e:
        print("Unexpected error occurred.", e )
addresses

                                              Address      lat     long
0       AMZN CAN Fulfillment Svcs, ULC , Toronto , ON  43.6532 -79.3832
1                            Accenture , Toronto , ON  43.6496 -79.3796
2                          BFS Capital , Toronto , ON  43.6481 -79.3847
3                  BMO Financial Group , Toronto , ON  43.6486 -79.3817
4   BMW Group Financial Services Canada , Toronto ...  43.8875 -79.3823
5                             Birdseye , Toronto , ON  43.6766 -79.5878
6                            Capgemini , Toronto , ON  43.6497 -79.3867
7                             Ceridian , Toronto , ON  43.7463  -79.409
8               Colliers International , Toronto , ON  43.6472 -79.3791
9                             Coursera , Toronto , ON  43.6518 -79.3802
10                          Desjardins , Toronto , ON  43.6489 -79.3786
11                          Enhance IT , Toronto , ON  43.8062 -79.4212
12                              Exiger , Toronto , ON   43.648 -79.3777
13            HarperCollins Publishers , Toronto , ON  43.6503 -79.3796
14                              Intact , Toronto , ON  43.6585 -79.3914
15                      Loblaw Digital , Toronto , ON   43.639   -79.42
16                           PagerDuty , Toronto , ON  43.6417 -79.4123
17            Patriot One Technologies , Toronto , ON  45.3787 -75.7415
18              Postmedia Network Inc. , Toronto , ON  43.6719  -79.378
19         Qode Social Media Marketing , Toronto , ON  43.6477 -79.3921
20                                 RBC , Toronto , ON  43.6631 -79.4026
21                            Resolver , Toronto , ON  43.6479 -79.3929
22                   Saatchi & Saatchi , Toronto , ON  43.6707 -79.3825
23                            SickKids , Toronto , ON  43.6573 -79.3873
24                             TD Bank , Toronto , ON  43.6482 -79.3809
25                               TKEES , Toronto , ON  43.6487 -79.3958
26                         Tenstorrent , Toronto , ON   43.721 -79.3321
27                            VersaPay , Toronto , ON  43.6496 -79.3771

In [64]:
# addresses.to_excel("company.xlsx")
#exported geocodes to company.excel

In [65]:
!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library
import folium # map rendering library
from folium import plugins

# Matplotlib and associated plotting modules
import matplotlib.cm as cm

import matplotlib.colors as colors

import seaborn as sns

# import k-means from clustering stage
from sklearn.cluster import KMeans


!pip install geopandas
!pip install geopy

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Requirement already satisfied: geopandas in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (0.8.1)
Requirement already satisfied: pandas>=0.23.0 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from geopandas) (1.0.5)
Requirement already satisfied: pyproj>=2.2.0 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from geopandas) (2.6.1.post1)
Requirement already satisfied: fiona in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from geopandas) (1.8.17)
Requirement already satisfied: shapely in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from geopandas) (1.7.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.0->geopandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from pandas>=0.23.0->geopandas) (1.18.5)
Requirement already satisfied: click<8,>=4.0 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (7.1.2)
Requirement already satisfied: click-plugins>=1.0 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: six>=1.7 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (1.15.0)
Requirement already satisfied: munch in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: attrs>=17 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (19.3.0)
Requirement already satisfied: cligj>=0.5 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from fiona->geopandas) (0.5.0)
Requirement already satisfied: geopy in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (2.0.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /Users/abhishekpadala/anaconda3/lib/python3.8/site-packages (from geopy) (1.50)

In [66]:
#toronto geocodes
latitude = 43.6532
longitude= -79.3832

map_toronto = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lt, lg, label in zip(addresses['lat'], addresses['long'], addresses['Address']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lt, lg],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_toronto)  
    
map_toronto

My residential preferences are :
Rent between 1000 to 2000, Pets = yes, Bedroom = 1, Type = condos or apartment.
scraped data from Rental.ca  #https://rentals.ca/toronto?rentrange=1000-2000&types=condo&types=apartment&beds=1%2B&pets=true
rental.xlsx have all the data about available residential places

In [76]:
rental_data = pd.read_excel('rental_data.xlsx')
rental_data.head()

,Unnamed: 0,Rent,Location,lat,long
0,0,"$1,750","70 Temperance St, Unit 4116,Toronto,Ontario",43.650530,-79.382148
1,1,"$1,900","197 Yonge Street St, Unit 2104,Toronto,Ontario",43.653525,-79.379238
2,2,"$1,700","403 Church St, Unit 1711,Toronto,Ontario",43.662066,-79.379337
3,3,"$2,100","25 Oxley St, Unit 413,Toronto,Ontario",43.646247,-79.394528
4,4,"$1,950","87 Peter St, Unit 2701,Toronto,Ontario",43.646944,-79.392397

In [78]:
rental_data.drop(['Unnamed: 0'], axis=1, inplace=True)
rental_data.head()

KeyError: "['Unnamed: 0'] not found in axis"

In [80]:
rental_data['Rent'] = rental_data['Rent'].str.replace('$', '')

In [81]:
rental_data.head()
rental_data.to_csv('rental_data1.csv')

In [ ]:
find neighbourhood based on location